// Queries (catalog MG-015 – MG-046, without the trap rows MG-032 – MG-034, MG-039, MG-040, which are
// in MultigraphPreconditionTests.swift): `edges(between:and:)` / `edges(from:to:)` oldest copy
// first, `edgeCount(between:and:)`, `contains(edge:)` (false, never a trap, for a non-vertex),
// self-loops twice in an undirected row and once in each directed row, degrees counting copies and
// a loop twice, and the rows of a freshly built graph (each edge appended at u, then at v).
// Generated from cases.md by swiftgen.py; see README.md.

import GraphProtocols
import Multigraphs
import Testing

@Suite("Multigraphs queries: copies, loops, degrees, rows")
struct MultigraphQueryTests {
    @Test("MG-015 two copies, both orientations kept")
    func mg015() {
        // Pseudograph V []; E [0–1, 1–0]; edges(between: 0, and: 1) / edges(between: 1, and: 0) / edgeCount(between: 0, and: 1)
        let graph = Pseudograph<Int>(vertices: [] as [Int], edges: [UndirectedEdge(0, 1), UndirectedEdge(1, 0)])
        #expect(Array(graph.edges(between: 0, and: 1)) == [0, 1])
        #expect(graph.edges(between: 0, and: 1).count == 2)
        #expect(Array(graph.edges(between: 1, and: 0)) == [0, 1])
        #expect(graph.edges(between: 1, and: 0).count == 2)
        #expect(graph.edgeCount(between: 0, and: 1) == 2)
        // Final state.
        #expect(Array(graph.vertices) == [0, 1])
        #expect(graph.edges.map { [$0.u, $0.v] } == [[0, 1], [1, 0]])
        #expect(graph.vertexCount == 2)
        #expect(graph.edgeCount == 2)
        #expect(Array(graph.neighbors(of: 0)) == [1, 1])
        #expect(Array(graph.incidentEdges(of: 0)) == [0, 1])
        #expect(Array(graph.neighbors(of: 1)) == [0, 0])
        #expect(Array(graph.incidentEdges(of: 1)) == [0, 1])
        #expect(Array(graph.edges(between: 0, and: 1)) == [0, 1])
        #expect(graph.edgeCount(between: 0, and: 1) == 2)
    }

    @Test("MG-016 three copies")
    func mg016() {
        // Pseudograph V []; E [0–1, 0–1, 0–1]; edges(between: 0, and: 1) / edgeCount(between: 1, and: 0) / degree(of: 0) / degree(of: 1)
        let graph = Pseudograph<Int>(vertices: [] as [Int], edges: [UndirectedEdge(0, 1), UndirectedEdge(0, 1), UndirectedEdge(0, 1)])
        #expect(Array(graph.edges(between: 0, and: 1)) == [0, 1, 2])
        #expect(graph.edges(between: 0, and: 1).count == 3)
        #expect(graph.edgeCount(between: 1, and: 0) == 3)
        #expect(graph.degree(of: 0) == 3)
        #expect(graph.degree(of: 1) == 3)
        // Final state.
        #expect(Array(graph.vertices) == [0, 1])
        #expect(graph.edges.map { [$0.u, $0.v] } == [[0, 1], [0, 1], [0, 1]])
        #expect(graph.vertexCount == 2)
        #expect(graph.edgeCount == 3)
        #expect(Array(graph.neighbors(of: 0)) == [1, 1, 1])
        #expect(Array(graph.incidentEdges(of: 0)) == [0, 1, 2])
        #expect(Array(graph.neighbors(of: 1)) == [0, 0, 0])
        #expect(Array(graph.incidentEdges(of: 1)) == [0, 1, 2])
        #expect(Array(graph.edges(between: 0, and: 1)) == [0, 1, 2])
        #expect(graph.edgeCount(between: 0, and: 1) == 3)
    }

    @Test("MG-017 copies interleaved with other edges")
    func mg017() {
        // Pseudograph V []; E [0–1, 1–2, 0–1, 2–0, 1–0]; edges(between: 0, and: 1) / edges(between: 1, and: 2) / edges(between: 0, and: 2) / edgeCount(between: 0, and: 1)
        let graph = Pseudograph<Int>(vertices: [] as [Int], edges: [UndirectedEdge(0, 1), UndirectedEdge(1, 2), UndirectedEdge(0, 1), UndirectedEdge(2, 0), UndirectedEdge(1, 0)])
        #expect(Array(graph.edges(between: 0, and: 1)) == [0, 2, 4])
        #expect(graph.edges(between: 0, and: 1).count == 3)
        #expect(Array(graph.edges(between: 1, and: 2)) == [1])
        #expect(graph.edges(between: 1, and: 2).count == 1)
        #expect(Array(graph.edges(between: 0, and: 2)) == [3])
        #expect(graph.edges(between: 0, and: 2).count == 1)
        #expect(graph.edgeCount(between: 0, and: 1) == 3)
        // Final state.
        #expect(Array(graph.vertices) == [0, 1, 2])
        #expect(graph.edges.map { [$0.u, $0.v] } == [[0, 1], [1, 2], [0, 1], [2, 0], [1, 0]])
        #expect(graph.vertexCount == 3)
        #expect(graph.edgeCount == 5)
        #expect(Array(graph.neighbors(of: 0)) == [1, 1, 2, 1])
        #expect(Array(graph.incidentEdges(of: 0)) == [0, 2, 3, 4])
        #expect(Array(graph.neighbors(of: 1)) == [0, 2, 0, 0])
        #expect(Array(graph.incidentEdges(of: 1)) == [0, 1, 2, 4])
        #expect(Array(graph.neighbors(of: 2)) == [1, 0])
        #expect(Array(graph.incidentEdges(of: 2)) == [1, 3])
        #expect(Array(graph.edges(between: 0, and: 1)) == [0, 2, 4])
        #expect(graph.edgeCount(between: 0, and: 1) == 3)
        #expect(Array(graph.edges(between: 1, and: 2)) == [1])
        #expect(graph.edgeCount(between: 1, and: 2) == 1)
        #expect(Array(graph.edges(between: 2, and: 0)) == [3])
        #expect(graph.edgeCount(between: 2, and: 0) == 1)
    }

    @Test("MG-018 absent pair: empty, 0, false")
    func mg018() {
        // Pseudograph V [0, 1, 2]; E [0–1]; edges(between: 0, and: 2) / edgeCount(between: 0, and: 2) / contains(edge: UndirectedEdge(0, 2))
        let graph = Pseudograph<Int>(vertices: [0, 1, 2], edges: [UndirectedEdge(0, 1)])
        #expect(Array(graph.edges(between: 0, and: 2)) == [] as [Int])
        #expect(graph.edges(between: 0, and: 2).count == 0)
        #expect(graph.edgeCount(between: 0, and: 2) == 0)
        #expect(graph.contains(edge: UndirectedEdge(0, 2)) == false)
        // Final state.
        #expect(Array(graph.vertices) == [0, 1, 2])
        #expect(graph.edges.map { [$0.u, $0.v] } == [[0, 1]])
        #expect(graph.vertexCount == 3)
        #expect(graph.edgeCount == 1)
        #expect(Array(graph.neighbors(of: 0)) == [1])
        #expect(Array(graph.incidentEdges(of: 0)) == [0])
        #expect(Array(graph.neighbors(of: 1)) == [0])
        #expect(Array(graph.incidentEdges(of: 1)) == [0])
        #expect(Array(graph.neighbors(of: 2)) == [] as [Int])
        #expect(Array(graph.incidentEdges(of: 2)) == [] as [Int])
        #expect(Array(graph.edges(between: 0, and: 1)) == [0])
        #expect(graph.edgeCount(between: 0, and: 1) == 1)
    }

    @Test("MG-019 non-vertex: empty, 0, false, no trap")
    func mg019() {
        // Pseudograph V [0, 1]; E [0–1]; edges(between: 0, and: 9) / edgeCount(between: 9, and: 9) / contains(edge: UndirectedEdge(9, 0))
        let graph = Pseudograph<Int>(vertices: [0, 1], edges: [UndirectedEdge(0, 1)])
        #expect(Array(graph.edges(between: 0, and: 9)) == [] as [Int])
        #expect(graph.edges(between: 0, and: 9).count == 0)
        #expect(graph.edgeCount(between: 9, and: 9) == 0)
        #expect(graph.contains(edge: UndirectedEdge(9, 0)) == false)
        // Final state.
        #expect(Array(graph.vertices) == [0, 1])
        #expect(graph.edges.map { [$0.u, $0.v] } == [[0, 1]])
        #expect(graph.vertexCount == 2)
        #expect(graph.edgeCount == 1)
        #expect(Array(graph.neighbors(of: 0)) == [1])
        #expect(Array(graph.incidentEdges(of: 0)) == [0])
        #expect(Array(graph.neighbors(of: 1)) == [0])
        #expect(Array(graph.incidentEdges(of: 1)) == [0])
        #expect(Array(graph.edges(between: 0, and: 1)) == [0])
        #expect(graph.edgeCount(between: 0, and: 1) == 1)
    }

    @Test("MG-020 directed copies are directional")
    func mg020() {
        // DirectedPseudograph V []; E [0→1, 0→1, 1→0]; edges(from: 0, to: 1) / edges(from: 1, to: 0) / edgeCount(from: 0, to: 1) / edgeCount(from: 1, to: 0) / contains(edge: DirectedEdge(from: 1, to: 0))
        let graph = DirectedPseudograph<Int>(vertices: [] as [Int], edges: [DirectedEdge(from: 0, to: 1), DirectedEdge(from: 0, to: 1), DirectedEdge(from: 1, to: 0)])
        #expect(Array(graph.edges(from: 0, to: 1)) == [0, 1])
        #expect(graph.edges(from: 0, to: 1).count == 2)
        #expect(Array(graph.edges(from: 1, to: 0)) == [2])
        #expect(graph.edges(from: 1, to: 0).count == 1)
        #expect(graph.edgeCount(from: 0, to: 1) == 2)
        #expect(graph.edgeCount(from: 1, to: 0) == 1)
        #expect(graph.contains(edge: DirectedEdge(from: 1, to: 0)) == true)
        // Final state.
        #expect(Array(graph.vertices) == [0, 1])
        #expect(graph.edges.map { [$0.source, $0.target] } == [[0, 1], [0, 1], [1, 0]])
        #expect(graph.vertexCount == 2)
        #expect(graph.edgeCount == 3)
        #expect(Array(graph.successors(of: 0)) == [1, 1])
        #expect(Array(graph.outEdges(of: 0)) == [0, 1])
        #expect(Array(graph.predecessors(of: 0)) == [1])
        #expect(Array(graph.inEdges(of: 0)) == [2])
        #expect(Array(graph.successors(of: 1)) == [0])
        #expect(Array(graph.outEdges(of: 1)) == [2])
        #expect(Array(graph.predecessors(of: 1)) == [0, 0])
        #expect(Array(graph.inEdges(of: 1)) == [0, 1])
        #expect(Array(graph.edges(from: 0, to: 1)) == [0, 1])
        #expect(graph.edgeCount(from: 0, to: 1) == 2)
        #expect(Array(graph.edges(from: 1, to: 0)) == [2])
        #expect(graph.edgeCount(from: 1, to: 0) == 1)
    }

    @Test("MG-021 directed non-vertex")
    func mg021() {
        // DirectedPseudograph V [0]; E []; edges(from: 0, to: 7) / edgeCount(from: 7, to: 0) / contains(edge: DirectedEdge(from: 7, to: 7))
        let graph = DirectedPseudograph<Int>(vertices: [0], edges: [] as [DirectedEdge<Int>])
        #expect(Array(graph.edges(from: 0, to: 7)) == [] as [Int])
        #expect(graph.edges(from: 0, to: 7).count == 0)
        #expect(graph.edgeCount(from: 7, to: 0) == 0)
        #expect(graph.contains(edge: DirectedEdge(from: 7, to: 7)) == false)
        // Final state.
        #expect(Array(graph.vertices) == [0])
        #expect(graph.edges.map { [$0.source, $0.target] } == [] as [[Int]])
        #expect(graph.vertexCount == 1)
        #expect(graph.edgeCount == 0)
        #expect(Array(graph.successors(of: 0)) == [] as [Int])
        #expect(Array(graph.outEdges(of: 0)) == [] as [Int])
        #expect(Array(graph.predecessors(of: 0)) == [] as [Int])
        #expect(Array(graph.inEdges(of: 0)) == [] as [Int])
    }

    @Test("MG-022 multigraph copies")
    func mg022() throws {
        // Multigraph V []; E [0–1, 0–1, 1–2]; edges(between: 1, and: 0) / edgeCount(between: 0, and: 1)
        let graph = try #require(Multigraph<Int>(vertices: [] as [Int], edges: [UndirectedEdge(0, 1), UndirectedEdge(0, 1), UndirectedEdge(1, 2)]))
        #expect(Array(graph.edges(between: 1, and: 0)) == [0, 1])
        #expect(graph.edges(between: 1, and: 0).count == 2)
        #expect(graph.edgeCount(between: 0, and: 1) == 2)
        // Final state.
        #expect(Array(graph.vertices) == [0, 1, 2])
        #expect(graph.edges.map { [$0.u, $0.v] } == [[0, 1], [0, 1], [1, 2]])
        #expect(graph.vertexCount == 3)
        #expect(graph.edgeCount == 3)
        #expect(Array(graph.neighbors(of: 0)) == [1, 1])
        #expect(Array(graph.incidentEdges(of: 0)) == [0, 1])
        #expect(Array(graph.neighbors(of: 1)) == [0, 0, 2])
        #expect(Array(graph.incidentEdges(of: 1)) == [0, 1, 2])
        #expect(Array(graph.neighbors(of: 2)) == [1])
        #expect(Array(graph.incidentEdges(of: 2)) == [2])
        #expect(Array(graph.edges(between: 0, and: 1)) == [0, 1])
        #expect(graph.edgeCount(between: 0, and: 1) == 2)
        #expect(Array(graph.edges(between: 1, and: 2)) == [2])
        #expect(graph.edgeCount(between: 1, and: 2) == 1)
    }

    @Test("MG-023 directed multigraph copies")
    func mg023() throws {
        // DirectedMultigraph V []; E [0→1, 0→1, 1→0, 1→0]; edges(from: 1, to: 0) / edgeCount(from: 0, to: 1)
        let graph = try #require(DirectedMultigraph<Int>(vertices: [] as [Int], edges: [DirectedEdge(from: 0, to: 1), DirectedEdge(from: 0, to: 1), DirectedEdge(from: 1, to: 0), DirectedEdge(from: 1, to: 0)]))
        #expect(Array(graph.edges(from: 1, to: 0)) == [2, 3])
        #expect(graph.edges(from: 1, to: 0).count == 2)
        #expect(graph.edgeCount(from: 0, to: 1) == 2)
        // Final state.
        #expect(Array(graph.vertices) == [0, 1])
        #expect(graph.edges.map { [$0.source, $0.target] } == [[0, 1], [0, 1], [1, 0], [1, 0]])
        #expect(graph.vertexCount == 2)
        #expect(graph.edgeCount == 4)
        #expect(Array(graph.successors(of: 0)) == [1, 1])
        #expect(Array(graph.outEdges(of: 0)) == [0, 1])
        #expect(Array(graph.predecessors(of: 0)) == [1, 1])
        #expect(Array(graph.inEdges(of: 0)) == [2, 3])
        #expect(Array(graph.successors(of: 1)) == [0, 0])
        #expect(Array(graph.outEdges(of: 1)) == [2, 3])
        #expect(Array(graph.predecessors(of: 1)) == [0, 0])
        #expect(Array(graph.inEdges(of: 1)) == [0, 1])
        #expect(Array(graph.edges(from: 0, to: 1)) == [0, 1])
        #expect(graph.edgeCount(from: 0, to: 1) == 2)
        #expect(Array(graph.edges(from: 1, to: 0)) == [2, 3])
        #expect(graph.edgeCount(from: 1, to: 0) == 2)
    }

    @Test("MG-024 ten copies")
    func mg024() {
        // Pseudograph V []; E [0–1, 0–1, 0–1, 0–1, 0–1, 0–1, 0–1, 0–1, 0–1, 0–1]; edgeCount(between: 0, and: 1) / degree(of: 0)
        let graph = Pseudograph<Int>(vertices: [] as [Int], edges: [UndirectedEdge(0, 1), UndirectedEdge(0, 1), UndirectedEdge(0, 1), UndirectedEdge(0, 1), UndirectedEdge(0, 1), UndirectedEdge(0, 1), UndirectedEdge(0, 1), UndirectedEdge(0, 1), UndirectedEdge(0, 1), UndirectedEdge(0, 1)])
        #expect(graph.edgeCount(between: 0, and: 1) == 10)
        #expect(graph.degree(of: 0) == 10)
        // Final state.
        #expect(Array(graph.vertices) == [0, 1])
        #expect(graph.edges.map { [$0.u, $0.v] } == [[0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1]])
        #expect(graph.vertexCount == 2)
        #expect(graph.edgeCount == 10)
        #expect(Array(graph.neighbors(of: 0)) == [1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
        #expect(Array(graph.incidentEdges(of: 0)) == [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
        #expect(Array(graph.neighbors(of: 1)) == [0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
        #expect(Array(graph.incidentEdges(of: 1)) == [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
        #expect(Array(graph.edges(between: 0, and: 1)) == [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
        #expect(graph.edgeCount(between: 0, and: 1) == 10)
    }

    @Test("MG-025 string copies")
    func mg025() {
        // Pseudograph V []; E ["a"–"b", "b"–"a", "a"–"b"]; edges(between: "b", and: "a")
        let graph = Pseudograph<String>(vertices: [] as [String], edges: [UndirectedEdge("a", "b"), UndirectedEdge("b", "a"), UndirectedEdge("a", "b")])
        #expect(Array(graph.edges(between: "b", and: "a")) == [0, 1, 2])
        #expect(graph.edges(between: "b", and: "a").count == 3)
        // Final state.
        #expect(Array(graph.vertices) == ["a", "b"])
        #expect(graph.edges.map { [$0.u, $0.v] } == [["a", "b"], ["b", "a"], ["a", "b"]])
        #expect(graph.vertexCount == 2)
        #expect(graph.edgeCount == 3)
        #expect(Array(graph.neighbors(of: "a")) == ["b", "b", "b"])
        #expect(Array(graph.incidentEdges(of: "a")) == [0, 1, 2])
        #expect(Array(graph.neighbors(of: "b")) == ["a", "a", "a"])
        #expect(Array(graph.incidentEdges(of: "b")) == [0, 1, 2])
        #expect(Array(graph.edges(between: "a", and: "b")) == [0, 1, 2])
        #expect(graph.edgeCount(between: "a", and: "b") == 3)
    }

    @Test("MG-026 one loop: listed twice in its row, degree 2")
    func mg026() {
        // Pseudograph V []; E [0–0]; degree(of: 0) / edges(between: 0, and: 0) / edgeCount(between: 0, and: 0)
        let graph = Pseudograph<Int>(vertices: [] as [Int], edges: [UndirectedEdge(0, 0)])
        #expect(graph.degree(of: 0) == 2)
        #expect(Array(graph.edges(between: 0, and: 0)) == [0])
        #expect(graph.edges(between: 0, and: 0).count == 1)
        #expect(graph.edgeCount(between: 0, and: 0) == 1)
        // Final state.
        #expect(Array(graph.vertices) == [0])
        #expect(graph.edges.map { [$0.u, $0.v] } == [[0, 0]])
        #expect(graph.vertexCount == 1)
        #expect(graph.edgeCount == 1)
        #expect(Array(graph.neighbors(of: 0)) == [0, 0])
        #expect(Array(graph.incidentEdges(of: 0)) == [0, 0])
        #expect(Array(graph.edges(between: 0, and: 0)) == [0])
        #expect(graph.edgeCount(between: 0, and: 0) == 1)
    }

    @Test("MG-027 two loops")
    func mg027() {
        // Pseudograph V []; E [0–0, 0–0]; degree(of: 0) / edges(between: 0, and: 0) / edgeCount(between: 0, and: 0)
        let graph = Pseudograph<Int>(vertices: [] as [Int], edges: [UndirectedEdge(0, 0), UndirectedEdge(0, 0)])
        #expect(graph.degree(of: 0) == 4)
        #expect(Array(graph.edges(between: 0, and: 0)) == [0, 1])
        #expect(graph.edges(between: 0, and: 0).count == 2)
        #expect(graph.edgeCount(between: 0, and: 0) == 2)
        // Final state.
        #expect(Array(graph.vertices) == [0])
        #expect(graph.edges.map { [$0.u, $0.v] } == [[0, 0], [0, 0]])
        #expect(graph.vertexCount == 1)
        #expect(graph.edgeCount == 2)
        #expect(Array(graph.neighbors(of: 0)) == [0, 0, 0, 0])
        #expect(Array(graph.incidentEdges(of: 0)) == [0, 0, 1, 1])
        #expect(Array(graph.edges(between: 0, and: 0)) == [0, 1])
        #expect(graph.edgeCount(between: 0, and: 0) == 2)
    }

    @Test("MG-028 loop beside an edge")
    func mg028() {
        // Pseudograph V []; E [0–1, 0–0, 1–0]; degree(of: 0) / degree(of: 1) / edges(between: 0, and: 0)
        let graph = Pseudograph<Int>(vertices: [] as [Int], edges: [UndirectedEdge(0, 1), UndirectedEdge(0, 0), UndirectedEdge(1, 0)])
        #expect(graph.degree(of: 0) == 4)
        #expect(graph.degree(of: 1) == 2)
        #expect(Array(graph.edges(between: 0, and: 0)) == [1])
        #expect(graph.edges(between: 0, and: 0).count == 1)
        // Final state.
        #expect(Array(graph.vertices) == [0, 1])
        #expect(graph.edges.map { [$0.u, $0.v] } == [[0, 1], [0, 0], [1, 0]])
        #expect(graph.vertexCount == 2)
        #expect(graph.edgeCount == 3)
        #expect(Array(graph.neighbors(of: 0)) == [1, 0, 0, 1])
        #expect(Array(graph.incidentEdges(of: 0)) == [0, 1, 1, 2])
        #expect(Array(graph.neighbors(of: 1)) == [0, 0])
        #expect(Array(graph.incidentEdges(of: 1)) == [0, 2])
        #expect(Array(graph.edges(between: 0, and: 1)) == [0, 2])
        #expect(graph.edgeCount(between: 0, and: 1) == 2)
        #expect(Array(graph.edges(between: 0, and: 0)) == [1])
        #expect(graph.edgeCount(between: 0, and: 0) == 1)
    }

    @Test("MG-029 loop on an isolated listed vertex")
    func mg029() {
        // Pseudograph V [0, 1]; E [1–1]; degree(of: 0) / degree(of: 1)
        let graph = Pseudograph<Int>(vertices: [0, 1], edges: [UndirectedEdge(1, 1)])
        #expect(graph.degree(of: 0) == 0)
        #expect(graph.degree(of: 1) == 2)
        // Final state.
        #expect(Array(graph.vertices) == [0, 1])
        #expect(graph.edges.map { [$0.u, $0.v] } == [[1, 1]])
        #expect(graph.vertexCount == 2)
        #expect(graph.edgeCount == 1)
        #expect(Array(graph.neighbors(of: 0)) == [] as [Int])
        #expect(Array(graph.incidentEdges(of: 0)) == [] as [Int])
        #expect(Array(graph.neighbors(of: 1)) == [1, 1])
        #expect(Array(graph.incidentEdges(of: 1)) == [0, 0])
        #expect(Array(graph.edges(between: 1, and: 1)) == [0])
        #expect(graph.edgeCount(between: 1, and: 1) == 1)
    }

    @Test("MG-030 directed loop: once out, once in")
    func mg030() {
        // DirectedPseudograph V []; E [0→0]; degrees(0) / edges(from: 0, to: 0)
        let graph = DirectedPseudograph<Int>(vertices: [] as [Int], edges: [DirectedEdge(from: 0, to: 0)])
        #expect(graph.outDegree(of: 0) == 1)
        #expect(graph.inDegree(of: 0) == 1)
        #expect(graph.degree(of: 0) == 2)
        #expect(Array(graph.edges(from: 0, to: 0)) == [0])
        #expect(graph.edges(from: 0, to: 0).count == 1)
        // Final state.
        #expect(Array(graph.vertices) == [0])
        #expect(graph.edges.map { [$0.source, $0.target] } == [[0, 0]])
        #expect(graph.vertexCount == 1)
        #expect(graph.edgeCount == 1)
        #expect(Array(graph.successors(of: 0)) == [0])
        #expect(Array(graph.outEdges(of: 0)) == [0])
        #expect(Array(graph.predecessors(of: 0)) == [0])
        #expect(Array(graph.inEdges(of: 0)) == [0])
        #expect(Array(graph.edges(from: 0, to: 0)) == [0])
        #expect(graph.edgeCount(from: 0, to: 0) == 1)
    }

    @Test("MG-031 directed two loops and an arc")
    func mg031() {
        // DirectedPseudograph V []; E [0→0, 0→1, 0→0]; degrees(0) / degrees(1) / edgeCount(from: 0, to: 0)
        let graph = DirectedPseudograph<Int>(vertices: [] as [Int], edges: [DirectedEdge(from: 0, to: 0), DirectedEdge(from: 0, to: 1), DirectedEdge(from: 0, to: 0)])
        #expect(graph.outDegree(of: 0) == 3)
        #expect(graph.inDegree(of: 0) == 2)
        #expect(graph.degree(of: 0) == 5)
        #expect(graph.outDegree(of: 1) == 0)
        #expect(graph.inDegree(of: 1) == 1)
        #expect(graph.degree(of: 1) == 1)
        #expect(graph.edgeCount(from: 0, to: 0) == 2)
        // Final state.
        #expect(Array(graph.vertices) == [0, 1])
        #expect(graph.edges.map { [$0.source, $0.target] } == [[0, 0], [0, 1], [0, 0]])
        #expect(graph.vertexCount == 2)
        #expect(graph.edgeCount == 3)
        #expect(Array(graph.successors(of: 0)) == [0, 1, 0])
        #expect(Array(graph.outEdges(of: 0)) == [0, 1, 2])
        #expect(Array(graph.predecessors(of: 0)) == [0, 0])
        #expect(Array(graph.inEdges(of: 0)) == [0, 2])
        #expect(Array(graph.successors(of: 1)) == [] as [Int])
        #expect(Array(graph.outEdges(of: 1)) == [] as [Int])
        #expect(Array(graph.predecessors(of: 1)) == [0])
        #expect(Array(graph.inEdges(of: 1)) == [1])
        #expect(Array(graph.edges(from: 0, to: 0)) == [0, 2])
        #expect(graph.edgeCount(from: 0, to: 0) == 2)
        #expect(Array(graph.edges(from: 0, to: 1)) == [1])
        #expect(graph.edgeCount(from: 0, to: 1) == 1)
    }

    @Test("MG-035 degrees count copies")
    func mg035() {
        // Pseudograph V []; E [0–1, 0–1, 0–2]; degree(of: 0) / degree(of: 1) / degree(of: 2)
        let graph = Pseudograph<Int>(vertices: [] as [Int], edges: [UndirectedEdge(0, 1), UndirectedEdge(0, 1), UndirectedEdge(0, 2)])
        #expect(graph.degree(of: 0) == 3)
        #expect(graph.degree(of: 1) == 2)
        #expect(graph.degree(of: 2) == 1)
        // Final state.
        #expect(Array(graph.vertices) == [0, 1, 2])
        #expect(graph.edges.map { [$0.u, $0.v] } == [[0, 1], [0, 1], [0, 2]])
        #expect(graph.vertexCount == 3)
        #expect(graph.edgeCount == 3)
        #expect(Array(graph.neighbors(of: 0)) == [1, 1, 2])
        #expect(Array(graph.incidentEdges(of: 0)) == [0, 1, 2])
        #expect(Array(graph.neighbors(of: 1)) == [0, 0])
        #expect(Array(graph.incidentEdges(of: 1)) == [0, 1])
        #expect(Array(graph.neighbors(of: 2)) == [0])
        #expect(Array(graph.incidentEdges(of: 2)) == [2])
        #expect(Array(graph.edges(between: 0, and: 1)) == [0, 1])
        #expect(graph.edgeCount(between: 0, and: 1) == 2)
        #expect(Array(graph.edges(between: 0, and: 2)) == [2])
        #expect(graph.edgeCount(between: 0, and: 2) == 1)
    }

    @Test("MG-036 sum is twice the edge count with loops")
    func mg036() {
        // Pseudograph V []; E [0–0, 0–1, 1–1, 1–1]; degree(of: 0) / degree(of: 1)
        let graph = Pseudograph<Int>(vertices: [] as [Int], edges: [UndirectedEdge(0, 0), UndirectedEdge(0, 1), UndirectedEdge(1, 1), UndirectedEdge(1, 1)])
        #expect(graph.degree(of: 0) == 3)
        #expect(graph.degree(of: 1) == 5)
        // Final state.
        #expect(Array(graph.vertices) == [0, 1])
        #expect(graph.edges.map { [$0.u, $0.v] } == [[0, 0], [0, 1], [1, 1], [1, 1]])
        #expect(graph.vertexCount == 2)
        #expect(graph.edgeCount == 4)
        #expect(Array(graph.neighbors(of: 0)) == [0, 0, 1])
        #expect(Array(graph.incidentEdges(of: 0)) == [0, 0, 1])
        #expect(Array(graph.neighbors(of: 1)) == [0, 1, 1, 1, 1])
        #expect(Array(graph.incidentEdges(of: 1)) == [1, 2, 2, 3, 3])
        #expect(Array(graph.edges(between: 0, and: 0)) == [0])
        #expect(graph.edgeCount(between: 0, and: 0) == 1)
        #expect(Array(graph.edges(between: 0, and: 1)) == [1])
        #expect(graph.edgeCount(between: 0, and: 1) == 1)
        #expect(Array(graph.edges(between: 1, and: 1)) == [2, 3])
        #expect(graph.edgeCount(between: 1, and: 1) == 2)
    }

    @Test("MG-037 isolated vertex 0")
    func mg037() {
        // Pseudograph V [0, 1]; E []; degree(of: 0)
        let graph = Pseudograph<Int>(vertices: [0, 1], edges: [] as [UndirectedEdge<Int>])
        #expect(graph.degree(of: 0) == 0)
        // Final state.
        #expect(Array(graph.vertices) == [0, 1])
        #expect(graph.edges.map { [$0.u, $0.v] } == [] as [[Int]])
        #expect(graph.vertexCount == 2)
        #expect(graph.edgeCount == 0)
        #expect(Array(graph.neighbors(of: 0)) == [] as [Int])
        #expect(Array(graph.incidentEdges(of: 0)) == [] as [Int])
        #expect(Array(graph.neighbors(of: 1)) == [] as [Int])
        #expect(Array(graph.incidentEdges(of: 1)) == [] as [Int])
    }

    @Test("MG-038 directed degrees")
    func mg038() {
        // DirectedPseudograph V []; E [0→1, 0→1, 1→0, 2→0]; degrees(0) / degrees(1) / degrees(2)
        let graph = DirectedPseudograph<Int>(vertices: [] as [Int], edges: [DirectedEdge(from: 0, to: 1), DirectedEdge(from: 0, to: 1), DirectedEdge(from: 1, to: 0), DirectedEdge(from: 2, to: 0)])
        #expect(graph.outDegree(of: 0) == 2)
        #expect(graph.inDegree(of: 0) == 2)
        #expect(graph.degree(of: 0) == 4)
        #expect(graph.outDegree(of: 1) == 1)
        #expect(graph.inDegree(of: 1) == 2)
        #expect(graph.degree(of: 1) == 3)
        #expect(graph.outDegree(of: 2) == 1)
        #expect(graph.inDegree(of: 2) == 0)
        #expect(graph.degree(of: 2) == 1)
        // Final state.
        #expect(Array(graph.vertices) == [0, 1, 2])
        #expect(graph.edges.map { [$0.source, $0.target] } == [[0, 1], [0, 1], [1, 0], [2, 0]])
        #expect(graph.vertexCount == 3)
        #expect(graph.edgeCount == 4)
        #expect(Array(graph.successors(of: 0)) == [1, 1])
        #expect(Array(graph.outEdges(of: 0)) == [0, 1])
        #expect(Array(graph.predecessors(of: 0)) == [1, 2])
        #expect(Array(graph.inEdges(of: 0)) == [2, 3])
        #expect(Array(graph.successors(of: 1)) == [0])
        #expect(Array(graph.outEdges(of: 1)) == [2])
        #expect(Array(graph.predecessors(of: 1)) == [0, 0])
        #expect(Array(graph.inEdges(of: 1)) == [0, 1])
        #expect(Array(graph.successors(of: 2)) == [0])
        #expect(Array(graph.outEdges(of: 2)) == [3])
        #expect(Array(graph.predecessors(of: 2)) == [] as [Int])
        #expect(Array(graph.inEdges(of: 2)) == [] as [Int])
        #expect(Array(graph.edges(from: 0, to: 1)) == [0, 1])
        #expect(graph.edgeCount(from: 0, to: 1) == 2)
        #expect(Array(graph.edges(from: 1, to: 0)) == [2])
        #expect(graph.edgeCount(from: 1, to: 0) == 1)
        #expect(Array(graph.edges(from: 2, to: 0)) == [3])
        #expect(graph.edgeCount(from: 2, to: 0) == 1)
    }

    @Test("MG-041 multigraph degrees")
    func mg041() throws {
        // Multigraph V []; E [0–1, 1–0, 1–2]; degree(of: 0) / degree(of: 1) / degree(of: 2)
        let graph = try #require(Multigraph<Int>(vertices: [] as [Int], edges: [UndirectedEdge(0, 1), UndirectedEdge(1, 0), UndirectedEdge(1, 2)]))
        #expect(graph.degree(of: 0) == 2)
        #expect(graph.degree(of: 1) == 3)
        #expect(graph.degree(of: 2) == 1)
        // Final state.
        #expect(Array(graph.vertices) == [0, 1, 2])
        #expect(graph.edges.map { [$0.u, $0.v] } == [[0, 1], [1, 0], [1, 2]])
        #expect(graph.vertexCount == 3)
        #expect(graph.edgeCount == 3)
        #expect(Array(graph.neighbors(of: 0)) == [1, 1])
        #expect(Array(graph.incidentEdges(of: 0)) == [0, 1])
        #expect(Array(graph.neighbors(of: 1)) == [0, 0, 2])
        #expect(Array(graph.incidentEdges(of: 1)) == [0, 1, 2])
        #expect(Array(graph.neighbors(of: 2)) == [1])
        #expect(Array(graph.incidentEdges(of: 2)) == [2])
        #expect(Array(graph.edges(between: 0, and: 1)) == [0, 1])
        #expect(graph.edgeCount(between: 0, and: 1) == 2)
        #expect(Array(graph.edges(between: 1, and: 2)) == [2])
        #expect(graph.edgeCount(between: 1, and: 2) == 1)
    }

    @Test("MG-042 rows in insertion order, u end then v end")
    func mg042() {
        // Pseudograph V []; E [0–1, 2–0, 0–0, 1–2]
        let graph = Pseudograph<Int>(vertices: [] as [Int], edges: [UndirectedEdge(0, 1), UndirectedEdge(2, 0), UndirectedEdge(0, 0), UndirectedEdge(1, 2)])
        // Final state.
        #expect(Array(graph.vertices) == [0, 1, 2])
        #expect(graph.edges.map { [$0.u, $0.v] } == [[0, 1], [2, 0], [0, 0], [1, 2]])
        #expect(graph.vertexCount == 3)
        #expect(graph.edgeCount == 4)
        #expect(Array(graph.neighbors(of: 0)) == [1, 2, 0, 0])
        #expect(Array(graph.incidentEdges(of: 0)) == [0, 1, 2, 2])
        #expect(Array(graph.neighbors(of: 1)) == [0, 2])
        #expect(Array(graph.incidentEdges(of: 1)) == [0, 3])
        #expect(Array(graph.neighbors(of: 2)) == [0, 1])
        #expect(Array(graph.incidentEdges(of: 2)) == [1, 3])
        #expect(Array(graph.edges(between: 0, and: 1)) == [0])
        #expect(graph.edgeCount(between: 0, and: 1) == 1)
        #expect(Array(graph.edges(between: 2, and: 0)) == [1])
        #expect(graph.edgeCount(between: 2, and: 0) == 1)
        #expect(Array(graph.edges(between: 0, and: 0)) == [2])
        #expect(graph.edgeCount(between: 0, and: 0) == 1)
        #expect(Array(graph.edges(between: 1, and: 2)) == [3])
        #expect(graph.edgeCount(between: 1, and: 2) == 1)
    }

    @Test("MG-043 loop's two ends adjacent in its row")
    func mg043() {
        // Pseudograph V []; E [0–1, 1–1, 1–2]
        let graph = Pseudograph<Int>(vertices: [] as [Int], edges: [UndirectedEdge(0, 1), UndirectedEdge(1, 1), UndirectedEdge(1, 2)])
        // Final state.
        #expect(Array(graph.vertices) == [0, 1, 2])
        #expect(graph.edges.map { [$0.u, $0.v] } == [[0, 1], [1, 1], [1, 2]])
        #expect(graph.vertexCount == 3)
        #expect(graph.edgeCount == 3)
        #expect(Array(graph.neighbors(of: 0)) == [1])
        #expect(Array(graph.incidentEdges(of: 0)) == [0])
        #expect(Array(graph.neighbors(of: 1)) == [0, 1, 1, 2])
        #expect(Array(graph.incidentEdges(of: 1)) == [0, 1, 1, 2])
        #expect(Array(graph.neighbors(of: 2)) == [1])
        #expect(Array(graph.incidentEdges(of: 2)) == [2])
        #expect(Array(graph.edges(between: 0, and: 1)) == [0])
        #expect(graph.edgeCount(between: 0, and: 1) == 1)
        #expect(Array(graph.edges(between: 1, and: 1)) == [1])
        #expect(graph.edgeCount(between: 1, and: 1) == 1)
        #expect(Array(graph.edges(between: 1, and: 2)) == [2])
        #expect(graph.edgeCount(between: 1, and: 2) == 1)
    }

    @Test("MG-044 directed rows: out by position, in by position")
    func mg044() {
        // DirectedPseudograph V []; E [0→1, 1→0, 0→1, 1→1, 2→1]
        let graph = DirectedPseudograph<Int>(vertices: [] as [Int], edges: [DirectedEdge(from: 0, to: 1), DirectedEdge(from: 1, to: 0), DirectedEdge(from: 0, to: 1), DirectedEdge(from: 1, to: 1), DirectedEdge(from: 2, to: 1)])
        // Final state.
        #expect(Array(graph.vertices) == [0, 1, 2])
        #expect(graph.edges.map { [$0.source, $0.target] } == [[0, 1], [1, 0], [0, 1], [1, 1], [2, 1]])
        #expect(graph.vertexCount == 3)
        #expect(graph.edgeCount == 5)
        #expect(Array(graph.successors(of: 0)) == [1, 1])
        #expect(Array(graph.outEdges(of: 0)) == [0, 2])
        #expect(Array(graph.predecessors(of: 0)) == [1])
        #expect(Array(graph.inEdges(of: 0)) == [1])
        #expect(Array(graph.successors(of: 1)) == [0, 1])
        #expect(Array(graph.outEdges(of: 1)) == [1, 3])
        #expect(Array(graph.predecessors(of: 1)) == [0, 0, 1, 2])
        #expect(Array(graph.inEdges(of: 1)) == [0, 2, 3, 4])
        #expect(Array(graph.successors(of: 2)) == [1])
        #expect(Array(graph.outEdges(of: 2)) == [4])
        #expect(Array(graph.predecessors(of: 2)) == [] as [Int])
        #expect(Array(graph.inEdges(of: 2)) == [] as [Int])
        #expect(Array(graph.edges(from: 0, to: 1)) == [0, 2])
        #expect(graph.edgeCount(from: 0, to: 1) == 2)
        #expect(Array(graph.edges(from: 1, to: 0)) == [1])
        #expect(graph.edgeCount(from: 1, to: 0) == 1)
        #expect(Array(graph.edges(from: 1, to: 1)) == [3])
        #expect(graph.edgeCount(from: 1, to: 1) == 1)
        #expect(Array(graph.edges(from: 2, to: 1)) == [4])
        #expect(graph.edgeCount(from: 2, to: 1) == 1)
    }

    @Test("MG-045 edge stored in given orientation")
    func mg045() {
        // Pseudograph V []; E [1–0, 0–1]
        let graph = Pseudograph<Int>(vertices: [] as [Int], edges: [UndirectedEdge(1, 0), UndirectedEdge(0, 1)])
        // Final state.
        #expect(Array(graph.vertices) == [1, 0])
        #expect(graph.edges.map { [$0.u, $0.v] } == [[1, 0], [0, 1]])
        #expect(graph.vertexCount == 2)
        #expect(graph.edgeCount == 2)
        #expect(Array(graph.neighbors(of: 1)) == [0, 0])
        #expect(Array(graph.incidentEdges(of: 1)) == [0, 1])
        #expect(Array(graph.neighbors(of: 0)) == [1, 1])
        #expect(Array(graph.incidentEdges(of: 0)) == [0, 1])
        #expect(Array(graph.edges(between: 1, and: 0)) == [0, 1])
        #expect(graph.edgeCount(between: 1, and: 0) == 2)
    }

    @Test("MG-046 star of copies")
    func mg046() {
        // Pseudograph V []; E [0–1, 0–2, 0–1, 0–3, 0–2]
        let graph = Pseudograph<Int>(vertices: [] as [Int], edges: [UndirectedEdge(0, 1), UndirectedEdge(0, 2), UndirectedEdge(0, 1), UndirectedEdge(0, 3), UndirectedEdge(0, 2)])
        // Final state.
        #expect(Array(graph.vertices) == [0, 1, 2, 3])
        #expect(graph.edges.map { [$0.u, $0.v] } == [[0, 1], [0, 2], [0, 1], [0, 3], [0, 2]])
        #expect(graph.vertexCount == 4)
        #expect(graph.edgeCount == 5)
        #expect(Array(graph.neighbors(of: 0)) == [1, 2, 1, 3, 2])
        #expect(Array(graph.incidentEdges(of: 0)) == [0, 1, 2, 3, 4])
        #expect(Array(graph.neighbors(of: 1)) == [0, 0])
        #expect(Array(graph.incidentEdges(of: 1)) == [0, 2])
        #expect(Array(graph.neighbors(of: 2)) == [0, 0])
        #expect(Array(graph.incidentEdges(of: 2)) == [1, 4])
        #expect(Array(graph.neighbors(of: 3)) == [0])
        #expect(Array(graph.incidentEdges(of: 3)) == [3])
        #expect(Array(graph.edges(between: 0, and: 1)) == [0, 2])
        #expect(graph.edgeCount(between: 0, and: 1) == 2)
        #expect(Array(graph.edges(between: 0, and: 2)) == [1, 4])
        #expect(graph.edgeCount(between: 0, and: 2) == 2)
        #expect(Array(graph.edges(between: 0, and: 3)) == [3])
        #expect(graph.edgeCount(between: 0, and: 3) == 1)
    }
}
