// swift-tools-version: 6.2
import PackageDescription

// GENERATED by scripts/modules.py — edit the table there, then run `just modules`.
//
// The published package definition. Bazel is the development build system; both are generated
// from the same table, and `just verify` builds and tests with both.

// Every target directory holds a BUILD.bazel, which SwiftPM must be told to ignore.
let bazelFiles = ["BUILD.bazel"]

let package = Package(
    name: "Grafluent",
    // macOS 15 / iOS 18 is the floor for `Synchronization.Mutex`, used by the test support target.
    // Revisit with open question 6 in README.md. Keep in step with .bazelrc.
    platforms: [.macOS(.v15), .iOS(.v18), .tvOS(.v18), .watchOS(.v11), .visionOS(.v2)],
    products: [
        .library(name: "Grafluent", targets: ["Grafluent"]),
        .library(name: "GraphProtocols", targets: ["GraphProtocols"]),
        .library(name: "Walks", targets: ["Walks"]),
        .library(name: "Semirings", targets: ["Semirings"]),
        .library(name: "PriorityQueueModule", targets: ["PriorityQueueModule"]),
        .library(name: "DisjointSetModule", targets: ["DisjointSetModule"]),
        .library(name: "AdjacencyListModule", targets: ["AdjacencyListModule"]),
        .library(name: "AdjacencyMatrixModule", targets: ["AdjacencyMatrixModule"]),
        .library(name: "IncidenceMatrixModule", targets: ["IncidenceMatrixModule"]),
        .library(name: "CompressedSparseRowModule", targets: ["CompressedSparseRowModule"]),
        .library(name: "EdgeListModule", targets: ["EdgeListModule"]),
        .library(name: "ImplicitGraphs", targets: ["ImplicitGraphs"]),
        .library(name: "LabeledGraphs", targets: ["LabeledGraphs"]),
        .library(name: "DirectedAcyclicGraphModule", targets: ["DirectedAcyclicGraphModule"]),
        .library(name: "Trees", targets: ["Trees"]),
        .library(name: "BipartiteGraphs", targets: ["BipartiteGraphs"]),
        .library(name: "Multigraphs", targets: ["Multigraphs"]),
        .library(name: "Hypergraphs", targets: ["Hypergraphs"]),
        .library(name: "FlowNetworks", targets: ["FlowNetworks"]),
        .library(name: "FunctionalGraphs", targets: ["FunctionalGraphs"]),
        .library(name: "GraphOperations", targets: ["GraphOperations"]),
        .library(name: "GraphProducts", targets: ["GraphProducts"]),
        .library(name: "Traversal", targets: ["Traversal"]),
        .library(name: "ShortestPaths", targets: ["ShortestPaths"]),
        .library(name: "SpanningTrees", targets: ["SpanningTrees"]),
        .library(name: "Connectivity", targets: ["Connectivity"]),
        .library(name: "Cycles", targets: ["Cycles"]),
        .library(name: "Tours", targets: ["Tours"]),
        .library(name: "Flows", targets: ["Flows"]),
        .library(name: "MatchingModule", targets: ["MatchingModule"]),
        .library(name: "ColoringModule", targets: ["ColoringModule"]),
        .library(name: "Cliques", targets: ["Cliques"]),
        .library(name: "Covering", targets: ["Covering"]),
        .library(name: "Centrality", targets: ["Centrality"]),
        .library(name: "CommunityDetection", targets: ["CommunityDetection"]),
        .library(name: "IsomorphismModule", targets: ["IsomorphismModule"]),
        .library(name: "Planarity", targets: ["Planarity"]),
        .library(name: "TreeAlgorithms", targets: ["TreeAlgorithms"]),
        .library(name: "Distances", targets: ["Distances"]),
        .library(name: "SpectralGraphTheory", targets: ["SpectralGraphTheory"]),
        .library(name: "NamedGraphs", targets: ["NamedGraphs"]),
        .library(name: "RandomGraphs", targets: ["RandomGraphs"]),
        .library(name: "GraphDrawing", targets: ["GraphDrawing"]),
        .library(name: "GraphFormats", targets: ["GraphFormats"]),
    ],
    dependencies: [
        .package(url: "https://github.com/apple/swift-collections", from: "1.3.0"),
        .package(url: "https://github.com/apple/swift-algorithms", from: "1.2.0"),
        .package(url: "https://github.com/x-sheep/swift-property-based", from: "2.0.1"),
    ],
    targets: [
        // Vocabulary
        .target(name: "GraphProtocols", dependencies: [.product(name: "Algorithms", package: "swift-algorithms")], exclude: bazelFiles),
        .target(name: "Walks", dependencies: ["GraphProtocols"], exclude: bazelFiles),
        .target(name: "Semirings", exclude: bazelFiles),
        // Data structures
        .target(name: "PriorityQueueModule", exclude: bazelFiles),
        .target(name: "DisjointSetModule", exclude: bazelFiles),
        // Representations
        .target(name: "AdjacencyListModule", dependencies: ["GraphProtocols"], exclude: bazelFiles),
        .target(name: "AdjacencyMatrixModule", dependencies: ["GraphProtocols", .product(name: "BitCollections", package: "swift-collections")], exclude: bazelFiles),
        .target(name: "IncidenceMatrixModule", dependencies: ["GraphProtocols"], exclude: bazelFiles),
        .target(name: "CompressedSparseRowModule", dependencies: ["GraphProtocols"], exclude: bazelFiles),
        .target(name: "EdgeListModule", dependencies: ["GraphProtocols"], exclude: bazelFiles),
        .target(name: "ImplicitGraphs", dependencies: ["GraphProtocols"], exclude: bazelFiles),
        .target(name: "LabeledGraphs", dependencies: ["GraphProtocols"], exclude: bazelFiles),
        // Structures
        .target(name: "DirectedAcyclicGraphModule", dependencies: ["GraphProtocols", "Walks"], exclude: bazelFiles),
        .target(name: "Trees", dependencies: ["GraphProtocols", "Walks"], exclude: bazelFiles),
        .target(name: "BipartiteGraphs", dependencies: ["GraphProtocols", "Walks", "AdjacencyListModule"], exclude: bazelFiles),
        .target(name: "Multigraphs", dependencies: ["GraphProtocols", "AdjacencyListModule"], exclude: bazelFiles),
        .target(name: "Hypergraphs", exclude: bazelFiles),
        .target(name: "FlowNetworks", dependencies: ["GraphProtocols"], exclude: bazelFiles),
        .target(name: "FunctionalGraphs", dependencies: ["GraphProtocols", "Walks"], exclude: bazelFiles),
        // Operations
        .target(name: "GraphOperations", dependencies: ["GraphProtocols", "DirectedAcyclicGraphModule"], exclude: bazelFiles),
        .target(name: "GraphProducts", dependencies: ["GraphProtocols"], exclude: bazelFiles),
        // Algorithms
        .target(name: "Traversal", dependencies: ["GraphProtocols", "Walks"], exclude: bazelFiles),
        .target(name: "ShortestPaths", dependencies: ["GraphProtocols", "Walks", "PriorityQueueModule"], exclude: bazelFiles),
        .target(name: "SpanningTrees", dependencies: ["GraphProtocols", "DisjointSetModule", "PriorityQueueModule"], exclude: bazelFiles),
        .target(name: "Connectivity", dependencies: ["GraphProtocols", "CompressedSparseRowModule"], exclude: bazelFiles),
        .target(name: "Cycles", dependencies: ["GraphProtocols", "Walks", "DisjointSetModule"], exclude: bazelFiles),
        .target(name: "Tours", dependencies: ["GraphProtocols", "Walks", "SpanningTrees", "MatchingModule"], exclude: bazelFiles),
        .target(name: "Flows", dependencies: ["GraphProtocols", "FlowNetworks", "Trees", "Traversal"], exclude: bazelFiles),
        .target(name: "MatchingModule", dependencies: ["GraphProtocols", "BipartiteGraphs"], exclude: bazelFiles),
        .target(name: "ColoringModule", dependencies: ["GraphProtocols", "BipartiteGraphs"], exclude: bazelFiles),
        .target(name: "Cliques", dependencies: ["GraphProtocols"], exclude: bazelFiles),
        .target(name: "Covering", dependencies: ["GraphProtocols", "MatchingModule", "BipartiteGraphs"], exclude: bazelFiles),
        .target(name: "Centrality", dependencies: ["GraphProtocols", "PriorityQueueModule"], exclude: bazelFiles),
        .target(name: "CommunityDetection", dependencies: ["GraphProtocols", "PriorityQueueModule"], exclude: bazelFiles),
        .target(name: "IsomorphismModule", dependencies: ["GraphProtocols"], exclude: bazelFiles),
        .target(name: "Planarity", dependencies: ["GraphProtocols", "Traversal"], exclude: bazelFiles),
        .target(name: "TreeAlgorithms", dependencies: ["GraphProtocols", "Trees", "Walks"], exclude: bazelFiles),
        .target(name: "Distances", dependencies: ["GraphProtocols", "Walks", "PriorityQueueModule"], exclude: bazelFiles),
        .target(name: "SpectralGraphTheory", dependencies: ["GraphProtocols"], exclude: bazelFiles),
        // Generators
        .target(name: "NamedGraphs", dependencies: ["GraphProtocols"], exclude: bazelFiles),
        .target(name: "RandomGraphs", dependencies: ["GraphProtocols"], exclude: bazelFiles),
        // Drawing
        .target(name: "GraphDrawing", dependencies: ["GraphProtocols", "Traversal", "Cycles", "SpectralGraphTheory"], exclude: bazelFiles),
        // Formats
        .target(name: "GraphFormats", dependencies: ["GraphProtocols"], exclude: bazelFiles),

        // Umbrella: `import Grafluent` imports every module.
        .target(name: "Grafluent", dependencies: ["GraphProtocols", "Walks", "Semirings", "PriorityQueueModule", "DisjointSetModule", "AdjacencyListModule", "AdjacencyMatrixModule", "IncidenceMatrixModule", "CompressedSparseRowModule", "EdgeListModule", "ImplicitGraphs", "LabeledGraphs", "DirectedAcyclicGraphModule", "Trees", "BipartiteGraphs", "Multigraphs", "Hypergraphs", "FlowNetworks", "FunctionalGraphs", "GraphOperations", "GraphProducts", "Traversal", "ShortestPaths", "SpanningTrees", "Connectivity", "Cycles", "Tours", "Flows", "MatchingModule", "ColoringModule", "Cliques", "Covering", "Centrality", "CommunityDetection", "IsomorphismModule", "Planarity", "TreeAlgorithms", "Distances", "SpectralGraphTheory", "NamedGraphs", "RandomGraphs", "GraphDrawing", "GraphFormats"], exclude: bazelFiles),

        // Shared fixtures, conformance checkers and instrumentation for every test target.
        .target(name: "GrafluentTestSupport", dependencies: ["GraphProtocols"], path: "Tests/GrafluentTestSupport", exclude: bazelFiles),

        .testTarget(name: "GrafluentTestSupportTests", dependencies: ["GraphProtocols", "GrafluentTestSupport"], exclude: bazelFiles),
        .testTarget(name: "AdjacencyListTests", dependencies: ["GraphProtocols", "AdjacencyListModule", "GrafluentTestSupport"], exclude: ["BUILD.bazel", "README.md"]),
        .testTarget(name: "UndirectedAdjacencyListTests", dependencies: ["GraphProtocols", "AdjacencyListModule", "GrafluentTestSupport"], exclude: ["BUILD.bazel", "README.md"]),
        .testTarget(name: "CompressedSparseRowTests", dependencies: ["GraphProtocols", "CompressedSparseRowModule", "AdjacencyListModule", "AdjacencyMatrixModule", "GrafluentTestSupport"], exclude: ["BUILD.bazel", "README.md"]),
        .testTarget(name: "AdjacencyMatrixTests", dependencies: ["GraphProtocols", "AdjacencyMatrixModule", "AdjacencyListModule", "GrafluentTestSupport", .product(name: "BitCollections", package: "swift-collections")], exclude: ["BUILD.bazel", "README.md"]),
        .testTarget(name: "EdgeListTests", dependencies: ["GraphProtocols", "EdgeListModule", "AdjacencyListModule", "AdjacencyMatrixModule", "CompressedSparseRowModule", "GrafluentTestSupport"], exclude: ["BUILD.bazel", "README.md"]),
        .testTarget(name: "TraversalTests", dependencies: ["GraphProtocols", "Traversal", "AdjacencyListModule", "AdjacencyMatrixModule", "CompressedSparseRowModule", "GrafluentTestSupport", "Walks"], exclude: ["BUILD.bazel", "README.md"]),
        .testTarget(name: "PriorityQueueTests", dependencies: ["PriorityQueueModule", "GrafluentTestSupport"], exclude: ["BUILD.bazel", "README.md"]),
        .testTarget(name: "DisjointSetTests", dependencies: ["DisjointSetModule", "GrafluentTestSupport"], exclude: ["BUILD.bazel", "README.md"]),
        .testTarget(name: "ShortestPathsTests", dependencies: ["GraphProtocols", "ShortestPaths", "Traversal", "AdjacencyListModule", "AdjacencyMatrixModule", "CompressedSparseRowModule", "GrafluentTestSupport", .product(name: "PropertyBased", package: "swift-property-based"), "Walks"], exclude: ["BUILD.bazel", "README.md"]),
        .testTarget(name: "SpanningTreesTests", dependencies: ["GraphProtocols", "SpanningTrees", "AdjacencyListModule", "AdjacencyMatrixModule", "CompressedSparseRowModule", "GrafluentTestSupport", .product(name: "PropertyBased", package: "swift-property-based")], exclude: ["BUILD.bazel", "README.md"]),
        .testTarget(name: "WalksTests", dependencies: ["GraphProtocols", "Walks", "AdjacencyListModule", "AdjacencyMatrixModule", "CompressedSparseRowModule", "GrafluentTestSupport", .product(name: "PropertyBased", package: "swift-property-based")], exclude: ["BUILD.bazel", "README.md"]),
        .testTarget(name: "CyclesTests", dependencies: ["GraphProtocols", "Cycles", "Walks", "Traversal", "AdjacencyListModule", "AdjacencyMatrixModule", "CompressedSparseRowModule", "GrafluentTestSupport", .product(name: "PropertyBased", package: "swift-property-based")], exclude: ["BUILD.bazel", "README.md"]),
        .testTarget(name: "TreesTests", dependencies: ["GraphProtocols", "Trees", "Walks", "Cycles", "AdjacencyListModule", "CompressedSparseRowModule", "GrafluentTestSupport", .product(name: "PropertyBased", package: "swift-property-based")], exclude: ["BUILD.bazel", "README.md"]),
        .testTarget(name: "TreeAlgorithmsTests", dependencies: ["GraphProtocols", "Trees", "TreeAlgorithms", "Walks", "AdjacencyListModule", "GrafluentTestSupport", .product(name: "PropertyBased", package: "swift-property-based")], exclude: ["BUILD.bazel", "README.md"]),
        .testTarget(name: "DistancesTests", dependencies: ["GraphProtocols", "Distances", "Walks", "Trees", "TreeAlgorithms", "AdjacencyListModule", "AdjacencyMatrixModule", "CompressedSparseRowModule", "GrafluentTestSupport", .product(name: "PropertyBased", package: "swift-property-based")], exclude: ["BUILD.bazel", "README.md"]),
        .testTarget(name: "CliquesTests", dependencies: ["GraphProtocols", "Cliques", "AdjacencyListModule", "AdjacencyMatrixModule", "CompressedSparseRowModule", "GrafluentTestSupport", .product(name: "PropertyBased", package: "swift-property-based")], exclude: ["BUILD.bazel", "README.md"]),
        .testTarget(name: "CommunityDetectionTests", dependencies: ["GraphProtocols", "CommunityDetection", "AdjacencyListModule", "AdjacencyMatrixModule", "CompressedSparseRowModule", "Connectivity", "GrafluentTestSupport", .product(name: "PropertyBased", package: "swift-property-based")], exclude: ["BUILD.bazel", "README.md"]),
        .testTarget(name: "BipartiteGraphsTests", dependencies: ["GraphProtocols", "BipartiteGraphs", "Walks", "AdjacencyListModule", "AdjacencyMatrixModule", "CompressedSparseRowModule", "GrafluentTestSupport", .product(name: "PropertyBased", package: "swift-property-based")], exclude: ["BUILD.bazel", "README.md"]),
        .testTarget(name: "MatchingModuleTests", dependencies: ["GraphProtocols", "MatchingModule", "BipartiteGraphs", "AdjacencyListModule", "AdjacencyMatrixModule", "CompressedSparseRowModule", "GrafluentTestSupport", .product(name: "PropertyBased", package: "swift-property-based")], exclude: ["BUILD.bazel", "README.md"]),
        .testTarget(name: "CoveringTests", dependencies: ["GraphProtocols", "Covering", "MatchingModule", "BipartiteGraphs", "AdjacencyListModule", "AdjacencyMatrixModule", "CompressedSparseRowModule", "GrafluentTestSupport", .product(name: "PropertyBased", package: "swift-property-based")], exclude: ["BUILD.bazel", "README.md"]),
        .testTarget(name: "MultigraphsTests", dependencies: ["GraphProtocols", "Multigraphs", "AdjacencyListModule", "GrafluentTestSupport", .product(name: "PropertyBased", package: "swift-property-based")], exclude: ["BUILD.bazel", "README.md"]),
        .testTarget(name: "CentralityTests", dependencies: ["GraphProtocols", "Centrality", "AdjacencyListModule", "AdjacencyMatrixModule", "CompressedSparseRowModule", "GrafluentTestSupport", .product(name: "PropertyBased", package: "swift-property-based")], exclude: ["BUILD.bazel", "README.md"]),
        .testTarget(name: "ConnectivityTests", dependencies: ["GraphProtocols", "Connectivity", "Traversal", "AdjacencyListModule", "AdjacencyMatrixModule", "CompressedSparseRowModule", "GrafluentTestSupport", .product(name: "PropertyBased", package: "swift-property-based")], exclude: ["BUILD.bazel", "README.md"]),
        .testTarget(name: "GraphProtocolsTests", dependencies: ["GraphProtocols", "Traversal", "AdjacencyListModule", "AdjacencyMatrixModule", "CompressedSparseRowModule", "EdgeListModule", "GrafluentTestSupport", .product(name: "BitCollections", package: "swift-collections")], exclude: ["BUILD.bazel", "README.md"]),
    ]
)
