// swift-tools-version: 6.0
import PackageDescription

// GENERATED by scripts/modules.py. Dependency-resolution manifest for Bazel
// (rules_swift_package_manager); it lists the same packages as the root Package.swift.
// After changing it, run `just resolve`.
let package = Package(
    name: "GrafluentDependencies",
    platforms: [.macOS("15.0")],
    dependencies: [
        .package(url: "https://github.com/apple/swift-collections", from: "1.3.0"),
        .package(url: "https://github.com/apple/swift-algorithms", from: "1.2.0"),
        .package(url: "https://github.com/x-sheep/swift-property-based", from: "2.0.1"),
    ]
)
