#!/usr/bin/env python3
"""Planted-bug (mutation) testing with mutant schemata.

Mutants are written by hand, one file per module in scripts/mutants/<Module>.py, as a list of
`Mutant(name, file, old, new, mode)`. Every mutant is compiled into one build of a scratch copy of
the package, each behind a runtime switch (Muter's "mutant schemata"), so the package is built
once rather than once per mutant:

    mode "expr":  old  ->  (__mutant(k) ? (new) : (old))   an expression
    mode "stmt":  old  ->  if __mutant(k) { new } else { old }   whole statements

`old` must occur once in the file, or `nth` picks the occurrence.
The environment variable GRAFLUENT_MUTANT picks the live mutant. Each mutant then runs the test
bundles named by the spec, several at once, and a run stops at its first failing test. A mutant is
caught when a test fails, the process crashes, or it runs past the time limit; it survived when
every test passes. A survivor needs a test or a note saying why it is equivalent.

    python3 scripts/mutate.py ShortestPaths            # every mutant
    python3 scripts/mutate.py ShortestPaths rotate     # the named ones
    python3 scripts/mutate.py ShortestPaths --jobs 2

The scratch copy lives in .build/mutation/ and is kept between runs, so later builds are
incremental. The real sources are never written.
"""

import argparse
import dataclasses
import os
import re
import runpy
import signal
import subprocess
import sys
import threading
import time
from concurrent.futures import ThreadPoolExecutor

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WORK = os.path.join(ROOT, ".build", "mutation")
SWIFT = ["env", "-u", "TOOLCHAINS", "xcrun", "--toolchain", "default", "swift"]

SWITCH = """\
// Generated by scripts/mutate.py in the mutation workspace only.
#if canImport(Darwin)
import Darwin
#elseif canImport(Glibc)
import Glibc
#endif

@usableFromInline let _activeMutant: Int = getenv("GRAFLUENT_MUTANT").map { Int(atoi($0)) } ?? -1

@usableFromInline @inline(never)
func __mutant(_ k: Int) -> Bool { _activeMutant == k }
"""


@dataclasses.dataclass
class Mutant:
    name: str
    file: str
    old: str
    new: str
    mode: str = "expr"
    # Which occurrence of `old` to mutate when it occurs more than once (0 is the first).
    nth: int | None = None


def load_spec(module):
    path = os.path.join(ROOT, "scripts", "mutants", f"{module}.py")
    spec = runpy.run_path(path, init_globals={"Mutant": Mutant})
    return spec["MUTANTS"], spec["TESTS"]


def sync_workspace():
    os.makedirs(WORK, exist_ok=True)
    # -c compares checksums so a file rewritten with the same contents keeps its mtime and does
    # not rebuild; --delete drops the previous run's switch files and schemata.
    for item in ["Package.swift", "Sources", "Tests"]:
        subprocess.run(["rsync", "-a", "-c", "--delete", os.path.join(ROOT, item), WORK], check=True)


def apply_schemata(module, mutants):
    by_file = {}
    for k, m in enumerate(mutants):
        by_file.setdefault(m.file, []).append((k, m))
    for file, entries in by_file.items():
        path = os.path.join(WORK, "Sources", module, file)
        with open(path) as f:
            text = f.read()
        for k, m in entries:
            count = text.count(m.old)
            if (m.nth is None and count != 1) or (m.nth is not None and m.nth >= count):
                sys.exit(f"{m.name}: the old text occurs {count} times in {file}")
            if m.mode == "expr":
                replacement = f"(__mutant({k}) ? ({m.new}) : ({m.old}))"
            elif m.mode == "stmt":
                indent = re.match(r"\s*", m.old).group(0)
                replacement = f"{indent}if __mutant({k}) {{\n{m.new or indent + '()'}\n{indent}}} else {{\n{m.old}\n{indent}}}"
            else:
                sys.exit(f"{m.name}: unknown mode {m.mode}")
            at = -1
            for _ in range((m.nth or 0) + 1):
                at = text.index(m.old, at + 1)
            text = text[:at] + replacement + text[at + len(m.old):]
        with open(path, "w") as f:
            f.write(text)
    with open(os.path.join(WORK, "Sources", module, "_MutantSwitch.swift"), "w") as f:
        f.write(SWITCH)


def build():
    started = time.time()
    result = subprocess.run(SWIFT + ["build", "--build-tests"], cwd=WORK, capture_output=True, text=True)
    if result.returncode != 0:
        errors = [line for line in result.stdout.splitlines() + result.stderr.splitlines() if "error:" in line]
        sys.exit("The schemata build failed:\n" + "\n".join(errors[:40] or result.stderr.splitlines()[-40:]))
    return time.time() - started


def test_command(bundle):
    developer = subprocess.run(["xcode-select", "-p"], capture_output=True, text=True).stdout.strip()
    swift = subprocess.run(["env", "-u", "TOOLCHAINS", "xcrun", "--toolchain", "default", "-f", "swift"],
                           capture_output=True, text=True).stdout.strip()
    helper = os.path.join(os.path.dirname(swift), "..", "libexec", "swift", "pm", "swiftpm-testing-helper")
    binary = os.path.join(WORK, ".build", "debug", f"{bundle}.xctest", "Contents", "MacOS", bundle)
    env = dict(os.environ)
    env["DYLD_FRAMEWORK_PATH"] = os.path.join(developer, "Platforms/MacOSX.platform/Developer/Library/Frameworks")
    env["DYLD_LIBRARY_PATH"] = os.path.join(developer, "Platforms/MacOSX.platform/Developer/usr/lib")
    env["NO_COLOR"] = "1"
    return [helper, "--test-bundle-path", binary, "--testing-library", "swift-testing"], env


FAILURE = re.compile(r"✘ Test (.*?) (?:recorded an issue|failed)")


def run_bundle(command, env, mutant, limit):
    """Returns (outcome, detail): outcome is "passed", "failed", "crashed" or "timed out"."""
    env = dict(env, GRAFLUENT_MUTANT=str(mutant))
    process = subprocess.Popen(command, env=env, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                               text=True, errors="replace", start_new_session=True)
    timer = threading.Timer(limit, lambda: os.killpg(process.pid, signal.SIGKILL))
    timer.start()
    failure = None
    tail = []
    try:
        for line in process.stdout:
            tail = (tail + [line.rstrip()])[-5:]
            match = FAILURE.search(line)
            if match:
                failure = match.group(1)
                os.killpg(process.pid, signal.SIGKILL)
                break
        process.wait()
    finally:
        timed_out = not timer.is_alive() and failure is None and process.returncode == -signal.SIGKILL
        timer.cancel()
    if failure:
        return "failed", failure
    if timed_out:
        return "timed out", f"after {limit:.0f} s"
    if process.returncode != 0:
        return "crashed", f"exit {process.returncode}: {tail[-1] if tail else ''}"
    return "passed", ""


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("module")
    parser.add_argument("names", nargs="*", help="run only these mutants")
    parser.add_argument("--jobs", type=int, default=max(1, (os.cpu_count() or 4) // 5))
    args = parser.parse_args()

    mutants, bundles = load_spec(args.module)
    names = {m.name for m in mutants}
    if len(names) != len(mutants):
        sys.exit("Mutant names must be unique")
    unknown = set(args.names) - names
    if unknown:
        sys.exit(f"No such mutants: {', '.join(sorted(unknown))}")

    sync_workspace()
    apply_schemata(args.module, mutants)
    print(f"Built {len(mutants)} mutants into one build in {build():.0f} s", flush=True)

    commands = [test_command(b) for b in bundles]
    baseline = time.time()
    for (command, env), bundle in zip(commands, bundles):
        outcome, detail = run_bundle(command, env, -1, 600)
        if outcome != "passed":
            sys.exit(f"{bundle} does not pass without a mutant ({outcome}: {detail})")
    baseline = time.time() - baseline
    # Running several bundles at once slows each one, so the limit is generous.
    limit = 3 * baseline + 30
    print(f"Unmutated tests pass in {baseline:.0f} s; each mutant gets {limit:.0f} s", flush=True)

    chosen = [(k, m) for k, m in enumerate(mutants) if not args.names or m.name in args.names]
    width = max(len(m.name) for _, m in chosen)
    lock = threading.Lock()
    survivors = []

    def run(item):
        k, m = item
        started = time.time()
        for (command, env), bundle in zip(commands, bundles):
            outcome, detail = run_bundle(command, env, k, limit)
            if outcome != "passed":
                with lock:
                    print(f"{m.name:<{width}}  caught   {time.time() - started:5.1f} s  {bundle}: {outcome} {detail}", flush=True)
                return
        with lock:
            survivors.append(m.name)
            print(f"{m.name:<{width}}  SURVIVED {time.time() - started:5.1f} s", flush=True)

    started = time.time()
    with ThreadPoolExecutor(max_workers=args.jobs) as pool:
        list(pool.map(run, chosen))
    print(f"{len(chosen) - len(survivors)} of {len(chosen)} caught in {time.time() - started:.0f} s"
          + (f"; survived: {', '.join(survivors)}" if survivors else ""))


if __name__ == "__main__":
    main()
