// swift-tools-version: 6.2
import PackageDescription

// GENERATED by scripts/modules.py (DIFFERENTIAL_DEPENDENCIES): edit the list there, then run `just modules`.
//
// Differential testing against NetworkX and scipy: this executable answers a batch of queries
// with the library, and scripts/differential.py asks the reference libraries the same questions
// and compares. In its own package so the library never depends on Foundation's JSON coding.
// `just diff` builds it through Bazel (Differential/BUILD.bazel); this package is the
// `--swiftpm` fallback. See Differential/README.md.

let products: [Target.Dependency] = ["GraphProtocols", "AdjacencyListModule", "ShortestPaths", "SpanningTrees", "Connectivity", "Walks", "Cycles", "Trees", "TreeAlgorithms", "Distances", "Cliques", "Centrality", "CommunityDetection", "BipartiteGraphs", "MatchingModule", "Covering", "ColoringModule", "Multigraphs", "Flows"].map { .product(name: $0, package: "Grafluent") }

let package = Package(
    name: "GrafluentDifferential",
    platforms: [.macOS(.v15)],
    dependencies: [.package(path: "..")],
    targets: [.executableTarget(name: "GrafluentDifferential", dependencies: products)]
)
